List<Map<String, dynamic>> data_dentist = [
  {
    "id": 1,
    "avatar": "images/drg_steven_armeda.jpg",
    "nama": "drg. Steven Armeda",
    "spesialis": "General Dentist",
    "rating": "5.0",
    "lokasi": "Siloam Clinic",
    "hari": "Every Monday",
    "waktu": "20.00 - 23.00",
    "gender": "Male",
  },
  {
    "id": 2,
    "avatar": "images/drg_rose_chaeng.jpg",
    "nama": "drg. Rose Chaeng",
    "spesialis": "Orthodontist",
    "rating": "4.9",
    "lokasi": "Lavalette Hospital",
    "hari": "Every Tuesday",
    "waktu": "16.00 - 19.00",
    "gender": "Female",
  },
  {
    "id": 3,
    "avatar": "images/drg_irene_kim.jpg",
    "nama": "drg. Irene Kim",
    "spesialis": "Surgery",
    "rating": "5.0",
    "lokasi": "Pondok Indah Hospital",
    "hari": "Every Wednesday",
    "waktu": "18.00 - 21.00",
    "gender": "Female",
  },
  {
    "id": 4,
    "avatar": "images/drg_suci_ariana.jpg",
    "nama": "drg. Suci Ariana",
    "spesialis": "General Dentist",
    "rating": "4.7",
    "lokasi": "AR Dental Care",
    "hari": "Every Thursday",
    "waktu": "12.00 - 15.00",
    "gender": "Female",
  }
];
